# Generated by Django 5.1.7 on 2025-03-16 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precipitation_probability', models.FloatField()),
                ('wind_spend', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='locations.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
